-- Auto-generated from Flathub appstream data
-- Edit descriptions to fit ~29 chars/line on 128x128 canvas
return {
  alpaca = { name="Alpaca", author="Jeffry Samuel Eduarte Rojas", desc="Chat with AI models" },
  amberol = { name="Amberol", author="Emmanuele Bassi", desc="Plays music, and nothing else" },
  apostrophe = { name="Apostrophe", author="Manuel Genoves", desc="Edit Markdown in style" },
  aria = { name="Aria", author="Mirthe Stam", desc="Classy music player" },
  atomix = { name="Atomix", author="Robert Roth", desc="Build molecules out of single atoms" },
  ["audio-sharing"] = { name="Audio Sharing", author="Felix Hacker", desc="Share your computer audio" },
  authenticator = { name="Authenticator", author="Bilal Elmoussaoui", desc="Generate two-factor codes" },
  bazaar = { name="Bazaar", author="The Bazaar Contributors", desc="Discover and manage applications" },
  biblioteca = { name="Biblioteca", author="Akshay Warrier", desc="Read GNOME documentation offline" },
  blanket = { name="Blanket", author="Rafael Mardojai CM", desc="Listen to ambient sounds" },
  boatswain = { name="Boatswain", author="Georges Basile Stavracas Neto", desc="Control your Elgato Stream Decks" },
  boxes = { name="Boxes", author="The GNOME Project", desc="Virtualization made simple" },
  brasero = { name="Brasero", author="The Brasero developers", desc="Create and copy CDs and DVDs" },
  brief = { name="Brief", author="Shone Binu", desc="Browse command-line cheatsheets" },
  builder = { name="Builder", author="Christian Hergert", desc="Create applications for GNOME" },
  calculator = { name="Calculator", author="The GNOME Project", desc="Perform arithmetic, scientific or financial calculations" },
  calendar = { name="Calendar", author="The GNOME Project", desc="Manage your schedule" },
  calls = { name="Calls", author="Julian Sparber, Evangelos Ribeiro Tzaras", desc="Make phone and SIP calls" },
  carburetor = { name="Carburetor", author="Tractor Team", desc="Browse anonymously" },
  cartridges = { name="Cartridges", author="kramo", desc="Launch all your games" },
  characters = { name="Characters", author="The GNOME Project", desc="Character map application" },
  cheese = { name="Cheese", author="The GNOME Project", desc="Take photos and videos with your webcam, with fun graphical effects" },
  ["chess-clock"] = { name="Chess Clock", author="Evangelos Ribeiro Tzaras", desc="Time games of over-the-board chess" },
  citations = { name="Citations", author="Maximiliano Sandoval", desc="Manage your bibliography" },
  clapper = { name="Clapper", author="Rafal Dziegiel", desc="Lean back and enjoy videos" },
  clocks = { name="Clocks", author="The GNOME Project", desc="Keep track of time" },
  collision = { name="Collision", author="Evangelos \"GeopJr\" Paterakis", desc="Check hashes for your files" },
  colorcode = { name="Color Code", author="oyajun", desc="Color Code to Resistance Value" },
  colorway = { name="Colorway", author="Lains", desc="Generate color pairings" },
  commit = { name="Commit", author="Sonny Piers", desc="Commit message editor" },
  connections = { name="Connections", author="The GNOME Project", desc="View and use other desktops" },
  contacts = { name="Contacts", author="The GNOME Project", desc="Manage your contacts" },
  cozy = { name="Cozy", author="Julian Geywitz", desc="Listen to audio books" },
  curtail = { name="Curtail", author="Hugo Posnic", desc="Compress your images" },
  decibels = { name="Audio Player", author="The GNOME Project", desc="Play audio files" },
  decoder = { name="Decoder", author="Bilal Elmoussaoui", desc="Scan and generate QR codes" },
  ["dejadup-backups"] = { name="Deja Dup Backups", author="Michael Terry", desc="Protect yourself from data loss" },
  ["dev-toolbox"] = { name="Dev Toolbox", author="Alessandro Iepure", desc="Dev tools at your fingertips" },
  dialect = { name="Dialect", author="The Dialect Authors", desc="Translate between languages" },
  ["disk-analyzer"] = { name="Disk Usage Analyzer", author="The GNOME Project", desc="Check folder sizes and available disk space" },
  drawing = { name="Drawing", author="Romain F. T.", desc="Edit screenshots or memes" },
  ["drum-machine"] = { name="Drum Machine", author="Revisto", desc="Create and play drum beats" },
  dspy = { name="D-Spy", author="Christian Hergert", desc="Analyze D-Bus connections" },
  ["ear-tag"] = { name="Ear Tag", author="knuxify", desc="Edit audio file tags" },
  elastic = { name="Elastic", author="Alice Mikhaylenko", desc="Design spring animations" },
  elfin = { name="Delfin", author="Avery", desc="Stream movies and TV shows from Jellyfin" },
  emblem = { name="Emblem", author="Maximiliano Sandoval", desc="Generate project avatars" },
  errands = { name="Errands", author="Vlad Krupinskii", desc="Manage your tasks" },
  evince = { name="Document Viewer", author="The Evince Developers", desc="Document viewer for popular document formats" },
  exchange = { name="Exchange", author="Shone Binu", desc="Convert between XML and Blueprint" },
  exhibit = { name="Exhibit", author="Nokse", desc="Preview your 3D models" },
  ["eye-of-gnome"] = { name="Eye of GNOME", author="The Eye of GNOME Team", desc="Browse and rotate images" },
  eyedropper = { name="Eyedropper", author="FineFindus", desc="Pick and format colors" },
  firmware = { name="Firmware", author="Richard Hughes", desc="Install firmware on devices" },
  fonts = { name="Fonts", author="The GNOME Project", desc="View fonts on your system" },
  forgesparks = { name="Forge Sparks", author="Rafael Mardojai CM", desc="Get Git forges notifications" },
  fragments = { name="Fragments", author="Felix Hacker", desc="Manage torrents" },
  gameeky = { name="Gameeky", author="Martin Abente Lahaye", desc="Play, create and learn" },
  ["gamepad-mirror"] = { name="Gamepad Mirror", author="Vendillah", desc="Visualize your gamepad's inputs" },
  gaphor = { name="Gaphor", author="Arjan J. Molenaar", desc="Simple UML and SysML modeling tool" },
  gelly = { name="Gelly", author="Austin Riba", desc="Music player for Jellyfin and Subsonic" },
  gimp = { name="GNU Image Manipulation Program", author="The GIMP team", desc="High-end image creation and manipulation" },
  gitte = { name="Gitte", author="Christian Kruse", desc="Simple Git client for GNOME" },
  health = { name="Health", author="Rasmus Cogitri Thomsen", desc="Track your fitness goals" },
  hieroglyphic = { name="Hieroglyphic", author="FineFindus", desc="Find LaTeX and Typst symbols" },
  iotas = { name="Iotas", author="Chris Heywood", desc="Simple note taking" },
  ["ip-lookup"] = { name="IP Lookup", author="Bytez", desc="Find info about an IP address" },
  jellybean = { name="Stockpile", author="Sunniva Lovstad", desc="Keep count of restockable items" },
  junction = { name="Junction", author="Sonny Piers", desc="Application chooser" },
  kasasa = { name="Kasasa", author="Kelvin Novais", desc="Snip and pin useful information" },
  keyrack = { name="Key Rack", author="Felix Hacker, Sophie Herold", desc="View and edit passwords" },
  komikku = { name="Komikku", author="Valery Febvre", desc="Discover and read manga & comics" },
  kooha = { name="Kooha", author="Dave Patrick Caberto", desc="Elegantly record your screen" },
  kotoba = { name="Kotoba", author="Haydn Trowell", desc="Japanese-English dictionary" },
  kuychi = { name="Kuychi", author="Naiara Gomez Castro", desc="Generate color palettes with all their shades and copy their hex codes" },
  laser = { name="Laser", author="Andreas Knoben", desc="Rip CDs with ease" },
  letters = { name="Letters", author="Satvik Patwardhan", desc="Word processor for GNOME" },
  logs = { name="Logs", author="The GNOME Project", desc="View detailed event logs for the system" },
  lorem = { name="Lorem", author="Maximiliano Sandoval", desc="Generate placeholder text" },
  maps = { name="Maps", author="The GNOME Project", desc="Find places around the world" },
  ["metadata-cleaner"] = { name="Metadata Cleaner", author="Metadata Cleaner Developers", desc="View and clean metadata in files" },
  metronome = { name="Metronome", author="Adrien Plazas", desc="Keep the tempo" },
  millisecond = { name="Millisecond", author="Gahel", desc="Optimize for low latency" },
  mousai = { name="Mousai", author="Dave Patrick Caberto", desc="Identify songs in seconds" },
  mousam = { name="Mousam", author="Amit Chaudhary", desc="Weather at a glance" },
  music = { name="Music", author="The GNOME Project", desc="Play and organize your music collection" },
  mypaint = { name="MyPaint", author="MyPaint Developers", desc="Painting program for digital artists" },
  nucleus = { name="Nucleus", author="Lo", desc="Browse the chemical elements" },
  obfuscate = { name="Obfuscate", author="Bilal Elmoussaoui", desc="Censor private information" },
  papers = { name="Document Viewer", author="The GNOME Project", desc="Read documents" },
  photos = { name="Photos", author="The GNOME Project", desc="Access, organize and share your photos on GNOME" },
  piccolo = { name="Piccolo", author="FatDawlf", desc="Color picking with style" },
  ["pika-backup"] = { name="Pika Backup", author="Small Mammal Collective", desc="Keep your data safe" },
  podcasts = { name="Podcasts", author="The Podcasts developers", desc="Listen to your favorite shows" },
  polari = { name="Polari", author="Florian Mullner", desc="Talk to people on IRC" },
  poliedros = { name="Poliedros", author="Diego C Sampaio", desc="Roll multi-type dice" },
  resources = { name="Resources", author="nokyan", desc="Keep an eye on system resources" },
  reversi = { name="Reversi", author="The Reversi Team", desc="Dominate the board in a classic reversi game, or play the reversed variant" },
  robots = { name="Robots", author="Andrey Kutejko", desc="Avoid the robots and make them crash into each other" },
  scriptorium = { name="Scriptorium", author="Christophe Gueret", desc="Design and write manuscripts" },
  seahorse = { name="Passwords and Keys", author="The GNOME Project", desc="Manage your passwords and encryption keys" },
  ["share-preview"] = { name="Share Preview", author="Rafael Mardojai CM", desc="Test social media cards locally" },
  shortwave = { name="Shortwave", author="Felix Hacker", desc="Listen to internet radio" },
  showtime = { name="Video Player", author="The GNOME Project", desc="Watch without distraction" },
  ["simple-scan"] = { name="Document Scanner", author="The GNOME Project", desc="Make a digital copy of your photos and documents" },
  sitra = { name="Sitra", author="Ronnie Nissan", desc="Get fonts from online sources" },
  solanum = { name="Solanum", author="Christopher Davis", desc="Balance working time and break time" },
  ["sound-recorder"] = { name="Sound Recorder", author="The GNOME Project", desc="A simple, modern sound recorder for GNOME" },
  ["ssh-pilot"] = { name="SSH Pilot", author="mFat", desc="Manage your servers with ease" },
  sudoku = { name="GNOME Sudoku", author="The GNOME Project", desc="Test yourself in the classic puzzle" },
  tangram = { name="Tangram", author="Sonny Piers", desc="Browser for your pinned tabs" },
  ["text-editor"] = { name="Text Editor", author="The GNOME Project", desc="Edit text files" },
  ["text-pieces"] = { name="Text Pieces", author="Gleb Smirnov", desc="Developer's scratchpad" },
  transmission = { name="Transmission", author="The Transmission Project", desc="Download and share files over BitTorrent" },
  tuba = { name="Tuba", author="Evangelos \"GeopJr\" Paterakis", desc="Browse the Fediverse" },
  typesetter = { name="Typesetter", author="Haydn Trowell", desc="Minimalist Typst editor" },
  valuta = { name="Valuta", author="Ideve Core", desc="Convert between currencies" },
  ["video-trimmer"] = { name="Video Trimmer", author="Ivan Molodetskikh", desc="Trim videos quickly" },
  videos = { name="Videos", author="The GNOME developers", desc="Play movies" },
  vinyl = { name="Vinyl", author="M23Snezhok", desc="Elegant music player" },
  warp = { name="Warp", author="Fina Wilke", desc="Fast and secure file transfer" },
  weather = { name="Weather", author="The GNOME Project", desc="Show weather conditions and forecast" },
  web = { name="Web", author="The GNOME Project", desc="Browse the web" },
  ["webfont-kit-generator"] = { name="Webfont Bundler", author="Rafael Mardojai CM", desc="Create @font-face kits easily" },
  wike = { name="Wike", author="Hugo Olabera", desc="Search and read Wikipedia articles" },
  workbench = { name="Workbench", author="Sonny Piers", desc="Prototype with GNOME technologies" },

  -- Manual entries (GNOME core / not on Flathub)
  ["bazaar-old"] = { name="Bazaar", author="GNOME", desc="App store concept" },
  ["color-manager"] = { name="Color Profile Viewer", author="GNOME", desc="Inspect and manage ICC color profiles" },
  deer = { name="Deer", author="GNOME", desc="A font browser" },
  disks = { name="Disks", author="GNOME", desc="Manage drives and media" },
  element = { name="Element", author="Element", desc="Secure messaging via the Matrix protocol" },
  esim = { name="eSIM", author="GNOME", desc="Manage embedded SIM profiles" },
  ["exercise-timer"] = { name="Exercise Timer", author="GNOME", desc="Time your workouts and rest periods" },
  ["file-shredder"] = { name="File Shredder", author="GNOME", desc="Securely delete files" },
  files = { name="Files", author="GNOME", desc="Access and organize your files" },
  gnurd = { name="Gnurd", author="GNOME", desc="Track your reading list" },
  help = { name="Help", author="GNOME", desc="Read the GNOME desktop help" },
  highscore = { name="Highscore", author="GNOME", desc="Track your game scores" },
  letterpress = { name="Letterpress", author="GNOME", desc="Create beautiful ASCII text art" },
  lipi = { name="Lipi", author="GNOME", desc="Practice handwriting on screen" },
  markets = { name="Markets", author="GNOME", desc="Track stock and crypto prices" },
  mesero = { name="Mesero", author="GNOME", desc="Manage restaurant orders" },
  mixtape = { name="Mixtape", author="GNOME", desc="Create and share playlists" },
  ["mutter-viewer"] = { name="Mutter Viewer", author="GNOME", desc="Debug the GNOME compositor" },
  navigator = { name="Navigator", author="GNOME", desc="Browse the web" },
  ["os-install"] = { name="OS Install", author="GNOME", desc="Install an operating system" },
  ["paper-clip"] = { name="Paper Clip", author="GNOME", desc="Edit PDF metadata" },
  plots = { name="Plots", author="GNOME", desc="Plot mathematical functions" },
  quertone = { name="Quertone", author="GNOME", desc="Play tones with your keyboard" },
  reflection = { name="Reflection", author="GNOME", desc="A personal journal" },
  rissole = { name="Rissole", author="GNOME", desc="A recipe manager" },
  rotor = { name="Rotor", author="GNOME", desc="Encode and decode text ciphers" },
  screenshot = { name="Screenshot", author="GNOME", desc="Capture the screen" },
  settings = { name="Settings", author="GNOME", desc="Configure your system" },
  shaper = { name="Shaper", author="GNOME", desc="Create and edit SVG shapes" },
  software = { name="Software", author="GNOME", desc="Find and install apps" },
  stereotype = { name="Stereotype", author="GNOME", desc="Sort files by type" },
  stickynotes = { name="Sticky Notes", author="GNOME", desc="Keep notes on your desktop" },
  ["system-monitor"] = { name="System Monitor", author="GNOME", desc="View system resources and processes" },
  tabs = { name="Tabs", author="GNOME", desc="Organize with tabbed browsing" },
  teddybear = { name="Teddybear", author="GNOME", desc="A cozy companion app" },
  terminal = { name="Terminal", author="GNOME", desc="Use the command line" },
  tour = { name="Tour", author="GNOME", desc="Get started with GNOME" },
  wallet = { name="Wallet", author="GNOME", desc="Manage payment methods" },
  webkit = { name="WebKit", author="Apple", desc="The web engine powering GNOME Web" },
  wifiauth = { name="Wi-Fi Auth", author="GNOME", desc="Share Wi-Fi via QR codes" },
}
