-- Auto-generated from Flathub appstream data
-- Edit descriptions to fit ~29 chars/line on 128x128 canvas
return {
  alpaca = { name="Alpaca", author="Jeffry Samuel Eduarte Rojas", desc="Chat with AI models", flatpak="com.jeffser.Alpaca"},
  amberol = { name="Amberol", author="Emmanuele Bassi", desc="Plays music, and nothing else", flatpak="io.bassi.Amberol"},
  apostrophe = { name="Apostrophe", author="Manuel Genoves", desc="Edit Markdown in style", flatpak="org.gnome.gitlab.somas.Apostrophe"},
  aria = { name="Aria", author="Mirthe Stam", desc="Classy music player"},
  atomix = { name="Atomix", author="Robert Roth", desc="Build molecules out of single atoms", flatpak="org.gnome.atomix"},
  ["audio-sharing"] = { name="Audio Sharing", author="Felix Hacker", desc="Share your computer audio", flatpak="de.haeckerfelix.AudioSharing"},
  authenticator = { name="Authenticator", author="Bilal Elmoussaoui", desc="Authenticate conveniently in two factor scenarios", flatpak="com.belmoussaoui.Authenticator"},
  bazaar = { name="Bazaar", author="The Bazaar Contributors", desc="Discover and manage applications", flatpak="io.github.kolunmi.Bazaar"},
  biblioteca = { name="Biblioteca", author="Akshay Warrier", desc="Read GNOME documentation offline", flatpak="app.drey.Biblioteca"},
  blanket = { name="Blanket", author="Rafael Mardojai CM", desc="Listen to ambient sounds in this polished white noise machine on steroids.", flatpak="com.rafaelmardojai.Blanket"},
  boatswain = { name="Boatswain", author="Georges Basile Stavracas Neto", desc="Control your Elgato Stream Deck", flatpak="com.feaneron.Boatswain"},
  boxes = { name="Boxes", author="The GNOME Project", desc="Virtualization made simple", flatpak="org.gnome.Boxes"},
  brief = { name="Brief", author="Shone Binu", desc="Browse command-line cheatsheets", flatpak="io.github.shonebinu.Brief"},
  builder = { name="Builder", author="Christian Hergert", desc="Create applications for GNOME in a polished IDE", flatpak="org.gnome.Builder"},
  calculator = { name="Calculator", author="The GNOME Project", desc="Perform arithmetic, scientific or financial calculations", flatpak="org.gnome.Calculator"},
  calendar = { name="Calendar", author="The GNOME Project", desc="Manage your schedule", flatpak="org.gnome.Calendar"},
  calls = { name="Calls", author="Julian Sparber, Evangelos Ribeiro Tzaras", desc="Make phone and SIP calls", flatpak="org.gnome.Calls"},
  calligraphy = { name="Calligraphy", author="Evangelos Paterakis", desc="Turn text into ASCII banners", flatpak="dev.geopjr.Calligraphy"},
  carburetor = { name="Carburetor", author="Tractor Team", desc="Browse anonymously", flatpak="io.frama.tractor.carburetor"},
  cartridges = { name="Cartridges", author="kramo", desc="Launch all your games", flatpak="page.kramo.Cartridges"},
  characters = { name="Characters", author="The GNOME Project", desc="Character map application", flatpak="org.gnome.Characters"},
  cheese = { name="Cheese", author="The GNOME Project", desc="Take photos and videos with your webcam, with fun graphical effects. Deprecated.", flatpak="org.gnome.Cheese"},
  ["chess-clock"] = { name="Chess Clock", author="Evangelos Ribeiro Tzaras", desc="Time games of over-the-board chess", flatpak="eu.fortysixandtwo.chessclock"},
  citations = { name="Citations", author="Maximiliano Sandoval", desc="Manage your bibliography", flatpak="org.gnome.World.Citations"},
  clocks = { name="Clocks", author="The GNOME Project", desc="Keep track of time", flatpak="org.gnome.clocks"},
  collision = { name="Collision", author="Evangelos \"GeopJr\" Paterakis", desc="Check hashes for your files", flatpak="dev.geopjr.Collision"},
  colorcode = { name="Color Code", author="oyajun", desc="Color Code to Resistance Value", flatpak="com.oyajun.ColorCode"},
  moviola = { name="Moviola", author="Fareed Hussain", desc="Video editor"},
  commit = { name="Commit", author="Sonny Piers", desc="Commit message editor", flatpak="re.sonny.Commit"},
  connections = { name="Connections", author="The GNOME Project", desc="View and use other desktops", flatpak="org.gnome.Connections"},
  contacts = { name="Contacts", author="The GNOME Project", desc="Manage your contacts", flatpak="org.gnome.Contacts"},
  cozy = { name="Cozy", author="Julian Geywitz", desc="Listen to audio books", flatpak="com.github.geigi.cozy"},
  curtail = { name="Curtail", author="Hugo Posnic", desc="Compress your images", flatpak="com.github.huluti.Curtail"},
  ["audio-player"] = { name="Audio Player", author="The GNOME Project", desc="Play audio files", flatpak="org.gnome.Decibels"},
  decibels = { name="Decibels", author="The GNOME Project", desc="Play audio files"},
  decoder = { name="Decoder", author="Bilal Elmoussaoui", desc="Scan and generate QR codes", flatpak="com.belmoussaoui.Decoder"},
  ["dejadup-backups"] = { name="Deja Dup Backups", author="Michael Terry", desc="Protect yourself from data loss", flatpak="org.gnome.DejaDup"},
  ["dev-toolbox"] = { name="Dev Toolbox", author="Alessandro Iepure", desc="Dev tools at your fingertips", flatpak="me.iepure.devtoolbox"},
  clapper = { name="Dew Duct", author="DaKnig", desc="Lean back and enjoy videos", flatpak="com.github.rafostar.Clapper"},
  dialect = { name="Dialect", author="The Dialect Authors", desc="Translate between languages", flatpak="app.drey.Dialect"},
  ["disk-analyzer"] = { name="Disk Usage Analyzer", author="The GNOME Project", desc="Check folder sizes and available disk space", flatpak="org.gnome.baobab"},
  railway = { name="Railway", author="Julian Schmidhuber", desc="Find all your travel information", flatpak="de.schmidhuberj.DieBahn"},
  ["drum-machine"] = { name="Drum Machine", author="Revisto", desc="Create and play drum beats", flatpak="io.github.revisto.drum-machine"},
  dspy = { name="D-Spy", author="Christian Hergert", desc="Analyze D-Bus connections", flatpak="org.gnome.dspy"},
  ["ear-tag"] = { name="Ear Tag", author="knuxify", desc="Edit audio file tags", flatpak="app.drey.EarTag"},
  elastic = { name="Elastic", author="Alice Mikhaylenko", desc="Design spring animations", flatpak="app.drey.Elastic"},
  elfin = { name="Delfin", author="Avery", desc="Stream movies and TV shows from Jellyfin", flatpak="cafe.avery.Delfin"},
  emblem = { name="Emblem", author="Maximiliano Sandoval", desc="Generate project avatars", flatpak="org.gnome.design.Emblem"},
  errands = { name="Errands", author="Vlad Krupinskii", desc="Manage your tasks", flatpak="io.github.mrvladus.List"},
  evince = { name="Document Viewer", author="The Evince Developers", desc="Document viewer for popular document formats", flatpak="org.gnome.Evince"},
  exchange = { name="Exchange", author="Shone Binu", desc="Convert between XML and Blueprint", flatpak="io.github.shonebinu.Exchange"},
  exhibit = { name="Exhibit", author="Nokse", desc="Preview your 3D models", flatpak="io.github.nokse22.Exhibit"},
  ["eye-of-gnome"] = { name="Eye of GNOME", author="The Eye of GNOME Team", desc="Browse and rotate images", flatpak="org.gnome.eog"},
  eyedropper = { name="Eyedropper", author="FineFindus", desc="Pick and format colors", flatpak="com.github.finefindus.eyedropper"},
  firmware = { name="Firmware", author="Richard Hughes", desc="Install firmware on devices", flatpak="org.gnome.Firmware"},
  fonts = { name="Fonts", author="The GNOME Project", desc="View fonts on your system", flatpak="org.gnome.font-viewer"},
  forgesparks = { name="Forge Sparks", author="Rafael Mardojai CM", desc="Get Git forges notifications", flatpak="com.mardojai.ForgeSparks"},
  fragments = { name="Fragments", author="Felix Hacker", desc="Manage torrents", flatpak="de.haeckerfelix.Fragments"},
  gameeky = { name="Gameeky", author="Martin Abente Lahaye", desc="Play, create and learn", flatpak="dev.tchx84.Gameeky"},
  ["gamepad-mirror"] = { name="Gamepad Mirror", author="Vendillah", desc="Visualize your gamepad's inputs", flatpak="page.codeberg.vendillah.GamepadMirror"},
  gaphor = { name="Gaphor", author="Arjan J. Molenaar", desc="Simple UML and SysML modeling tool", flatpak="org.gaphor.Gaphor"},
  gelly = { name="Gelly", author="Austin Riba", desc="Music player for Jellyfin and Subsonic", flatpak="io.m51.Gelly"},
  gimp = { name="GNU Image Manipulation Program", author="The GIMP team", desc="High-end image creation and manipulation", flatpak="org.gimp.GIMP"},
  gitte = { name="Gitte", author="Christian Kruse", desc="Simple Git client for GNOME", flatpak="de.wwwtech.gitte"},
  health = { name="Health", author="Rasmus Cogitri Thomsen", desc="Track your fitness goals", flatpak="dev.Cogitri.Health"},
  hieroglyphic = { name="Hieroglyphic", author="FineFindus", desc="Find LaTeX and Typst symbols", flatpak="io.github.finefindus.Hieroglyphic"},
  iotas = { name="Iotas", author="Chris Heywood", desc="Simple note taking", flatpak="org.gnome.World.Iotas"},
  ["ip-lookup"] = { name="IP Lookup", author="Bytez", desc="Find info about an IP address", flatpak="io.github.bytezz.IPLookup"},
  jellybean = { name="Stockpile", author="Sunniva Lovstad", desc="Keep count of restockable items", flatpak="garden.turtle.Jellybean"},
  junction = { name="Junction", author="Sonny Piers", desc="Application chooser", flatpak="re.sonny.Junction"},
  kasasa = { name="Kasasa", author="Kelvin Novais", desc="Snip and pin useful information", flatpak="io.github.kelvinnovais.Kasasa"},
  keyrack = { name="Key Rack", author="Felix Hacker, Sophie Herold", desc="View and edit passwords", flatpak="app.drey.KeyRack"},
  komikku = { name="Komikku", author="Valery Febvre", desc="Discover and read manga & comics", flatpak="info.febvre.Komikku"},
  kooha = { name="Kooha", author="Dave Patrick Caberto", desc="Elegantly record your screen", flatpak="io.github.seadve.Kooha"},
  kotoba = { name="Kotoba", author="Haydn Trowell", desc="Japanese-English dictionary", flatpak="net.trowell.kotoba"},
  kuychi = { name="Kuychi", author="Naiara Gomez Castro", desc="Generate color palettes with all their shades and copy their hex codes", flatpak="one.naiara.Kuychi"},
  laser = { name="Laser", author="Andreas Knoben", desc="Rip CDs with ease", flatpak="nl.andreasknoben.Laser"},
  letters = { name="Letters", author="Satvik Patwardhan", desc="Word processor for GNOME", flatpak="net.codelogistics.letters"},
  logs = { name="Logs", author="The GNOME Project", desc="View detailed event logs for the system", flatpak="org.gnome.Logs"},
  lorem = { name="Lorem", author="Maximiliano Sandoval", desc="Generate placeholder text", flatpak="org.gnome.design.Lorem"},
  maps = { name="Maps", author="The GNOME Project", desc="Find places around the world", flatpak="org.gnome.Maps"},
  ["metadata-cleaner"] = { name="Metadata Cleaner", author="Metadata Cleaner Developers", desc="View and clean metadata in files", flatpak="io.gitlab.metadatacleaner.metadatacleaner"},
  metronome = { name="Metronome", author="Adrien Plazas", desc="Keep the tempo", flatpak="com.adrienplazas.Metronome"},
  millisecond = { name="Millisecond", author="Gahel", desc="Optimize for low latency", flatpak="io.github.gaheldev.Millisecond"},
  mousai = { name="Mousai", author="Dave Patrick Caberto", desc="Identify songs in seconds", flatpak="io.github.seadve.Mousai"},
  mousam = { name="Mousam", author="Amit Chaudhary", desc="Weather at a glance", flatpak="io.github.amit9838.mousam"},
  music = { name="Music", author="The GNOME Project", desc="Play and organize your music collection", flatpak="org.gnome.Music"},
  mypaint = { name="MyPaint", author="MyPaint Developers", desc="Painting program for digital artists", flatpak="org.mypaint.MyPaint"},
  nucleus = { name="Nucleus", author="Lo", desc="Browse the chemical elements", flatpak="page.codeberg.lo_vely.Nucleus"},
  obfuscate = { name="Obfuscate", author="Bilal Elmoussaoui", desc="Censor private information", flatpak="com.belmoussaoui.Obfuscate"},
  papers = { name="Document Viewer", author="The GNOME Project", desc="Read documents", flatpak="org.gnome.Papers"},
  photos = { name="Photos", author="The GNOME Project", desc="Access, organize and share your photos on GNOME", flatpak="org.gnome.Photos"},
  piccolo = { name="Piccolo", author="Pixelo789", desc="Lightweight music player", flatpak="art.fatdawlf.Piccolo"},
  ["pika-backup"] = { name="Pika Backup", author="Small Mammal Collective", desc="Keep your data safe", flatpak="org.gnome.World.PikaBackup"},
  podcasts = { name="Podcasts", author="The Podcasts developers", desc="Listen to your favorite shows", flatpak="org.gnome.Podcasts"},
  polari = { name="Polari", author="Florian Mullner", desc="Talk to people on IRC", flatpak="org.gnome.Polari"},
  poliedros = { name="Poliedros", author="Diego C Sampaio", desc="Roll multi-type dice", flatpak="io.github.kriptolix.Poliedros"},
  resources = { name="Resources", author="nokyan", desc="Keep an eye on system resources", flatpak="net.nokyan.Resources"},
  reversi = { name="Reversi", author="The Reversi Team", desc="Dominate the board in a classic reversi game, or play the reversed variant", flatpak="org.gnome.Reversi"},
  robots = { name="Robots", author="Andrey Kutejko", desc="Avoid the robots and make them crash into each other", flatpak="org.gnome.Robots"},
  scriptorium = { name="Scriptorium", author="Christophe Gueret", desc="Design and write manuscripts", flatpak="io.github.cgueret.Scriptorium"},
  seahorse = { name="Passwords and Keys", author="The GNOME Project", desc="Manage your passwords and encryption keys", flatpak="org.gnome.seahorse.Application"},
  ["share-preview"] = { name="Share Preview", author="Rafael Mardojai CM", desc="Test social media cards locally", flatpak="com.rafaelmardojai.SharePreview"},
  shortwave = { name="Shortwave", author="Felix Hacker", desc="Listen to internet radio", flatpak="de.haeckerfelix.Shortwave"},
  showtime = { name="Video Player", author="The GNOME Project", desc="Watch without distraction", flatpak="org.gnome.Showtime"},
  ["simple-scan"] = { name="Document Scanner", author="The GNOME Project", desc="Make a digital copy of your photos and documents", flatpak="org.gnome.SimpleScan"},
  sitra = { name="Sitra", author="Ronnie Nissan", desc="Get fonts from online sources", flatpak="io.github.sitraorg.sitra"},
  solanum = { name="Solanum", author="Christopher Davis", desc="Balance working time and break time", flatpak="org.gnome.Solanum"},
  ["sound-recorder"] = { name="Sound Recorder", author="The GNOME Project", desc="A simple, modern sound recorder for GNOME", flatpak="org.gnome.SoundRecorder"},
  ["ssh-pilot"] = { name="SSH Pilot", author="mFat", desc="Manage your servers with ease", flatpak="io.github.mfat.sshpilot"},
  sudoku = { name="GNOME Sudoku", author="The GNOME Project", desc="Test yourself in the classic puzzle", flatpak="org.gnome.Sudoku"},
  tangram = { name="Tangram", author="Sonny Piers", desc="Browser for your pinned tabs", flatpak="re.sonny.Tangram"},
  ["text-editor"] = { name="Text Editor", author="The GNOME Project", desc="Edit text files", flatpak="org.gnome.TextEditor"},
  ["text-pieces"] = { name="Text Pieces", author="Gleb Smirnov", desc="Developer's scratchpad", flatpak="io.gitlab.liferooter.TextPieces"},
  transmission = { name="Transmission", author="The Transmission Project", desc="Download and share files over BitTorrent", flatpak="com.transmissionbt.Transmission"},
  tuba = { name="Tuba", author="Evangelos \"GeopJr\" Paterakis", desc="Browse the Fediverse", flatpak="dev.geopjr.Tuba"},
  typesetter = { name="Typesetter", author="Haydn Trowell", desc="Minimalist Typst editor", flatpak="net.trowell.typesetter"},
  valuta = { name="Valuta", author="Ideve Core", desc="Convert between currencies", flatpak="io.github.idevecore.Valuta"},
  ["video-trimmer"] = { name="Video Trimmer", author="Ivan Molodetskikh", desc="Trim videos quickly", flatpak="org.gnome.gitlab.YaLTeR.VideoTrimmer"},
  videos = { name="Videos", author="The GNOME developers", desc="Play movies", flatpak="org.gnome.Totem"},
  vinyl = { name="Vinyl", author="M23Snezhok", desc="Elegant music player", flatpak="page.codeberg.M23Snezhok.Vinyl"},
  warp = { name="Warp", author="Fina Wilke", desc="Fast and secure file transfer", flatpak="app.drey.Warp"},
  weather = { name="Weather", author="The GNOME Project", desc="Show weather conditions and forecast", flatpak="org.gnome.Weather"},
  web = { name="Web", author="The GNOME Project", desc="Browse the web", flatpak="org.gnome.Epiphany"},
  ["webfont-kit-generator"] = { name="Webfont Bundler", author="Rafael Mardojai CM", desc="Create @font-face kits easily", flatpak="com.rafaelmardojai.WebfontKitGenerator"},
  wike = { name="Wike", author="Hugo Olabera", desc="Search and read Wikipedia articles", flatpak="com.github.hugolabe.Wike"},
  workbench = { name="Workbench", author="Sonny Piers", desc="Prototype with GNOME technologies", flatpak="re.sonny.Workbench"},

  -- Manual entries (GNOME core / not on Flathub)
  ["bazaar-old"] = { name="Bazaar", author="GNOME", desc="App store concept"},
  ["color-manager"] = { name="Color Profile Viewer", author="GNOME", desc="Inspect and manage ICC color profiles"},
  deer = { name="Deer", author="GNOME", desc="A font browser"},
  disks = { name="Disks", author="GNOME", desc="Manage drives and media", flatpak="org.gnome.DiskUtility"},
  element = { name="Element", author="Element", desc="Secure messaging via the Matrix protocol", flatpak="im.riot.Riot"},
  esim = { name="eSIM", author="GNOME", desc="Manage embedded SIM profiles"},
  ["exercise-timer"] = { name="Exercise Timer", author="GNOME", desc="Time your workouts and rest periods"},
  ["file-shredder"] = { name="File Shredder", author="GNOME", desc="Securely delete files"},
  files = { name="Files", author="GNOME", desc="Access and organize your files", flatpak="org.gnome.Nautilus"},
  gnurd = { name="Gnurd", author="GNOME", desc="Track your reading list"},
  help = { name="Help", author="GNOME", desc="Read the GNOME desktop help"},
  highscore = { name="Highscore", author="Alexander Mikhaylenko", desc="Retro gaming with libretro"},
  letterpress = { name="Letterpress", author="GNOME", desc="Create beautiful ASCII text art"},
  lipi = { name="Lipi", author="GNOME", desc="Install fonts"},
  markets = { name="Markets", author="GNOME", desc="Track stock and crypto prices"},
  mesero = { name="Mesero", author="GNOME", desc="Wacom tablet configuration"},
  mixtape = { name="Mixtape", author="GNOME", desc="Create and share playlists"},
  ["mutter-viewer"] = { name="Mutter Viewer", author="GNOME", desc="Debug the GNOME compositor"},
  navigator = { name="Navigator", author="GNOME", desc="Browse the web"},
  ["os-install"] = { name="OS Install", author="GNOME", desc="Install an operating system"},
  ["paper-clip"] = { name="Paper Clip", author="Diego Ivan", desc="Edit PDF document metadata", flatpak="io.github.diegoivan.pdf_metadata_editor"},
  plots = { name="Plots", author="GNOME", desc="Plot mathematical functions"},
  qwertone = { name="Qwertone", author="Andrii Zymohliad", desc="A tuner and a metronome using QWERTY keyboard as a piano", flatpak="com.gitlab.azymohliad.Qwertone"},
  reflection = { name="Reflection", author="Modal Collective", desc="A collaborative text editor. Built with p2panda local-first peer to peer protocol."},
  rissole = { name="Rissole", author="GNOME", desc="A recipe manager"},
  rotor = { name="Rotor", author="GNOME", desc="Encode and decode text ciphers"},
  screenshot = { name="Screenshot", author="GNOME", desc="Capture the screen", flatpak="org.gnome.Screenshot"},
  settings = { name="Settings", author="GNOME", desc="Configure your system"},
  shaper = { name="Shaper", author="GNOME", desc="Create and edit SVG shapes"},
  software = { name="Software", author="GNOME", desc="Find and install apps"},
  stereotype = { name="Stereotype", author="GNOME", desc="Sort files by type"},
  keypunch = { name="Key Punch", author="Brage Fuglseth", desc="Practice your typing skills", flatpak="dev.bragefuglseth.Keypunch"},
  ["system-monitor"] = { name="System Monitor", author="GNOME", desc="View system resources and processes", flatpak="org.gnome.SystemMonitor"},
  tabs = { name="Tabs", author="GNOME", desc="View fretted string instrument tablature"},
  simba = { name="Simba", author="Lorenzo Paderi", desc="SMB configuration editor"},
  terminal = { name="Terminal", author="GNOME", desc="Use the command line"},
  ptyxis = { name="Ptyxis", author="Christian Hergert", desc="Container-oriented terminal", flatpak="app.devsuite.Ptyxis"},
  tour = { name="Tour", author="GNOME", desc="Get started with GNOME"},
  wallet = { name="Wallet", author="GNOME", desc="Manage payment methods"},
  webkit = { name="WebKit", author="Apple", desc="The web engine powering GNOME Web"},
  wifiauth = { name="Wi-Fi Auth", author="GNOME", desc="Share Wi-Fi via QR codes"},
}
